# Site settings
title: Higher Hangers Blog
header-img: img/home-bg.jpg
email: cleaverm@gmail.com
description: "These are awesome"
baseurl: "/startbootstrap-clean-blog-jekyll"
url: "http://blog.higherhangers.com"
twitter_username: higherhangers
github_username:  
facebook_username:  higherhangers

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
